### ISSUE TITLE
Issue about Lazy Render

### ISSUE THREAD

**Issue by Bruce-Yu2017** [vyakymenko/dipi#3]
Hi! I just used the lazy render directive to render a large table(2000+ rows, 50+ columns). When the table shows in my laptop(14'' screen), everything is fine, this directive increases the rendering speed a lot.
But when I move the chrome window to an external large monitor (24" or more), it's hard to scroll down in the table.
May I know the reason?
Thanks.

**Comment by vyakymenko** [comment]
Hi @Bruce-Yu2017 , thank you for the information, I will investigate this issue. But I can't reproduce it with big problems. Take a look at my [example](https://stackblitz.com/edit/dipi-seed-lazy-for-skfj5j).
